/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleButton {
        "appearance": string;
        "text": string;
    }
    interface ExampleModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isOpen": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLExampleButtonElement extends Components.ExampleButton, HTMLStencilElement {
    }
    var HTMLExampleButtonElement: {
        prototype: HTMLExampleButtonElement;
        new (): HTMLExampleButtonElement;
    };
    interface HTMLExampleModalElement extends Components.ExampleModal, HTMLStencilElement {
    }
    var HTMLExampleModalElement: {
        prototype: HTMLExampleModalElement;
        new (): HTMLExampleModalElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "example-button": HTMLExampleButtonElement;
        "example-modal": HTMLExampleModalElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExampleButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface ExampleModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isOpen"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "example-button": ExampleButton;
        "example-modal": ExampleModal;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-button": LocalJSX.ExampleButton & JSXBase.HTMLAttributes<HTMLExampleButtonElement>;
            "example-modal": LocalJSX.ExampleModal & JSXBase.HTMLAttributes<HTMLExampleModalElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
